wget -O B103.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=B103
wget -O B112.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=B112
wget -O B114.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=B114
wget -O B115.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=B115
wget -O E11A.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=E11A
wget -O E11B.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=E11B
wget -O T203.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T203
wget -O T204.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T204
wget -O T205.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T205
wget -O T223.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T223
wget -O T225.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T225
wget -O T226.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T226
wget -O T229.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T229
wget -O T231.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T231
wget -O U1.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U1
wget -O 'U1 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U1%20\(W\)
wget -O U10.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U10
wget -O U11.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U11
wget -O U12.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U12
wget -O U13.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U13
wget -O U14.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U14
wget -O U2.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U2
wget -O U201.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U201
wget -O U209.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U209
wget -O U222.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U222
wget -O U224.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U224
wget -O 'U224 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U224%20\(W\)
wget -O U2A.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U2A
wget -O U3.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U3
wget -O U4.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U4
wget -O U5.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U5
wget -O U6.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U6
wget -O 'U6 (W).json' --referer=http://jp.myrapid.com.my/query/route  http://jp.myrapid.com.my/query/route?route=U6%20\(W\)
wget -O U7.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U7
wget -O U8.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U8
wget -O 'U8 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U8%20\(W\)
wget -O BET7.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=BET7
wget -O T302.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T302
wget -O T304.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T304
wget -O T305.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T305
wget -O T307.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T307
wget -O T309.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T309
wget -O T312.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T312
wget -O T320.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T320
wget -O T323.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T323
wget -O T324.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T324
wget -O T327.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T327
wget -O T328.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T328
wget -O T329.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T329
wget -O T330.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T330
wget -O U20.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U20
wget -O U21.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U21
wget -O U23.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U23
wget -O U24.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U24
wget -O U25.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U25
wget -O U26.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U26
wget -O U27.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U27
wget -O U28.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U28
wget -O U29.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U29
wget -O U30.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U30
wget -O 'U30 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U30%20\(W\)
wget -O U31.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U31
wget -O 'U31 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U31%20\(W\)
wget -O U32.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U32
wget -O U33.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U33
wget -O U332.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U332
wget -O U34.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U34
wget -O U36.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U36
wget -O BET2.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=BET2
wget -O BET8.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=BET8
wget -O E1.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=E1
wget -O T405.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T405
wget -O T408.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T408
wget -O T416.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T416
wget -O T417.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T417
wget -O T418.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T418
wget -O T421.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T421
wget -O T422.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T422
wget -O T424.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T424
wget -O T427.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T427
wget -O T428.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T428
wget -O T430.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T430
wget -O T433.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T433
wget -O U40.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U40
wget -O 'U40 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U40%20\(W\)
wget -O U41.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U41
wget -O U410.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U410
wget -O U411.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U411
wget -O U412.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U412
wget -O U412A.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U412A
wget -O U415.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U415
wget -O U42.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U42
wget -O U429.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U429
wget -O U43.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U43
wget -O U432.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U432
wget -O U44.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U44
wget -O U45.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U45
wget -O U46.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U46
wget -O 'U46 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U46%20\(W\)
wget -O U47.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U47
wget -O U48.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U48
wget -O U49.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U49
wget -O BET3.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=BET3
wget -O BET4.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=BET4
wget -O T505.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T505
wget -O T507.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T507
wget -O T508.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T508
wget -O T509.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T509
wget -O T510.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T510
wget -O T511.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T511
wget -O T513.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T513
wget -O T515.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T515
wget -O T523.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T523
wget -O T527.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T527
wget -O T528.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T528
wget -O T529.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T529
wget -O T530.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T530
wget -O T600.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T600
wget -O U504.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U504
wget -O U60.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U60
wget -O 'U60 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U60%20\(W\)
wget -O U62.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U62
wget -O U63.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U63
wget -O U64.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U64
wget -O U65.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U65
wget -O U66.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U66
wget -O 'U66 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U66%20\(W\)
wget -O U68.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U68
wget -O 'U68 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U68%20\(W\)
wget -O U69.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U69
wget -O U70.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U70
wget -O U71.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U71
wget -O U72.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U72
wget -O U73.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U73
wget -O U74.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U74
wget -O U75.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U75
wget -O U75A.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U75A
wget -O U76.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U76
wget -O BET1.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=BET1
wget -O T601.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T601
wget -O T602.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T602
wget -O T603.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T603
wget -O T604.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T604
wget -O T607.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T607
wget -O T608.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T608
wget -O T610.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T610
wget -O T622.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T622
wget -O T624.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T624
wget -O T625.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T625
wget -O T626.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T626
wget -O T627.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T627
wget -O T628.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T628
wget -O T628B.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T628B
wget -O T629.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T629
wget -O T629B.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T629B
wget -O T631.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T631
wget -O T632.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T632
wget -O T633.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T633
wget -O T634.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T634
wget -O T635.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=T635
wget -O U605.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U605
wget -O U618.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U618
wget -O U623.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U623
wget -O 'U623 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U623%20\(W\)
wget -O U67.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U67
wget -O U80.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U80
wget -O 'U80 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U80%20\(W\)
wget -O U81.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U81
wget -O 'U81 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U81%20\(W\)
wget -O U82.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U82
wget -O 'U82 (W).json' --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U82%20\(W\)
wget -O U83.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U83
wget -O U84.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U84
wget -O U85.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U85
wget -O U86.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U86
wget -O U87.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U87
wget -O U88.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U88
wget -O U89.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U89
wget -O U90.json --referer=http://jp.myrapid.com.my/query/route http://jp.myrapid.com.my/query/route?route=U90